receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'spcs-metrics'
        http_sd_configs:
          - url: 'http://localhost:9003'

exporters:
  prometheus:
    endpoint: "0.0.0.0:9001"
    metric_expiration: 1m
    resource_to_telemetry_conversion:
      enabled: false

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [prometheus]
