-- rcr_customer_creds : setup.sql
-- SPCS sample where a Gradio service authenticates back to Snowflake using
-- customer-provided PATs (one per service user) stored in Snowflake SECRETs.
-- Run as ACCOUNTADMIN, then build/push the image, then run create_service.sql.
-- Doc: https://docs.snowflake.com/en/developer-guide/snowpark-container-services/spcs-execute-sql#connect-to-snowflake-by-using-customer-provided-credentials

USE ROLE ACCOUNTADMIN;

-- Customize names here. Defaults work for a clean sample install.
SET DB                  = 'app_db';
SET SCH                 = 'rcr';
SET WAREHOUSE           = 'app_wh';
SET COMPUTE_POOL        = 'app_compute_pool';
SET SERVICE_OWNER_ROLE  = 'service_owner_role';
SET FINANCE_ROLE        = 'finance_role';
SET MARKETING_ROLE      = 'marketing_role';
SET FINANCE_USER        = 'finance_service_user';
SET MARKETING_USER      = 'marketing_service_user';
SET NETWORK_RULE        = 'rcr_compute_pool_rule';
SET NETWORK_POLICY      = 'rcr_service_users_policy';

-- Roles
CREATE ROLE IF NOT EXISTS IDENTIFIER($SERVICE_OWNER_ROLE);
CREATE ROLE IF NOT EXISTS IDENTIFIER($FINANCE_ROLE);
CREATE ROLE IF NOT EXISTS IDENTIFIER($MARKETING_ROLE);

-- Database / schema / warehouse / compute pool, owned by finance_role.
CREATE DATABASE IF NOT EXISTS IDENTIFIER($DB);
GRANT OWNERSHIP ON DATABASE IDENTIFIER($DB) TO ROLE IDENTIFIER($FINANCE_ROLE) COPY CURRENT GRANTS;

USE DATABASE IDENTIFIER($DB);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($SCH);
GRANT OWNERSHIP ON SCHEMA IDENTIFIER($SCH) TO ROLE IDENTIFIER($FINANCE_ROLE) COPY CURRENT GRANTS;

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($WAREHOUSE)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE COMPUTE POOL IF NOT EXISTS IDENTIFIER($COMPUTE_POOL)
    MIN_NODES = 1 MAX_NODES = 1 INSTANCE_FAMILY = CPU_X64_XS AUTO_SUSPEND_SECS = 3600;

GRANT USAGE, MONITOR ON COMPUTE POOL IDENTIFIER($COMPUTE_POOL) TO ROLE IDENTIFIER($SERVICE_OWNER_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE) TO ROLE IDENTIFIER($SERVICE_OWNER_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE) TO ROLE IDENTIFIER($FINANCE_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE) TO ROLE IDENTIFIER($MARKETING_ROLE);
--- finance_role is the owner so it already has access
GRANT USAGE ON DATABASE IDENTIFIER($DB) TO ROLE IDENTIFIER($MARKETING_ROLE);
GRANT USAGE ON SCHEMA IDENTIFIER($SCH)  TO ROLE IDENTIFIER($MARKETING_ROLE);

-- Demo table + row access policy keyed on CURRENT_ROLE().
USE ROLE IDENTIFIER($FINANCE_ROLE);
USE DATABASE  IDENTIFIER($DB);
USE SCHEMA    IDENTIFIER($SCH);
USE WAREHOUSE IDENTIFIER($WAREHOUSE);

CREATE OR REPLACE TABLE team_data (
    id NUMBER AUTOINCREMENT, team STRING NOT NULL, region STRING, metric STRING, amount NUMBER(18,2)
);

INSERT INTO team_data (team, region, metric, amount) VALUES
    ('FINANCE',   'NA',   'Q1 revenue',  1820000.00),
    ('FINANCE',   'EMEA', 'Q1 revenue',   955000.00),
    ('FINANCE',   'APAC', 'Q1 revenue',   612300.00),
    ('FINANCE',   'NA',   'Q1 expenses', 740400.00),
    ('FINANCE',   'EMEA', 'Q1 expenses', 318900.00),
    ('MARKETING', 'NA',   'leads (MQL)',   4820.00),
    ('MARKETING', 'EMEA', 'leads (MQL)',   2105.00),
    ('MARKETING', 'APAC', 'leads (MQL)',    918.00),
    ('MARKETING', 'NA',   'spend ($)',  215000.00),
    ('MARKETING', 'EMEA', 'spend ($)',   88200.00);

CREATE OR REPLACE ROW ACCESS POLICY team_access_policy
    AS (team STRING) RETURNS BOOLEAN ->
           (CURRENT_ROLE() = $FINANCE_ROLE   AND team = 'FINANCE')
        OR (CURRENT_ROLE() = $MARKETING_ROLE AND team = 'MARKETING');

ALTER TABLE team_data ADD ROW ACCESS POLICY team_access_policy ON (team);

-- finance_role is the owner so it already has access
GRANT SELECT ON TABLE team_data TO ROLE IDENTIFIER($MARKETING_ROLE);

-- Service users (one per team), each with its data-access role as default.
USE ROLE ACCOUNTADMIN;

CREATE USER IF NOT EXISTS IDENTIFIER($FINANCE_USER)
    TYPE = SERVICE DEFAULT_ROLE = $FINANCE_ROLE DEFAULT_WAREHOUSE = $WAREHOUSE;
CREATE USER IF NOT EXISTS IDENTIFIER($MARKETING_USER)
    TYPE = SERVICE DEFAULT_ROLE = $MARKETING_ROLE DEFAULT_WAREHOUSE = $WAREHOUSE;

GRANT ROLE IDENTIFIER($FINANCE_ROLE)   TO USER IDENTIFIER($FINANCE_USER);
GRANT ROLE IDENTIFIER($MARKETING_ROLE) TO USER IDENTIFIER($MARKETING_USER);

-- Network rule + policy that lets PATs authenticate from the SPCS compute pool.
-- CREATE IF NOT EXISTS so re-running the script doesn't fail with
-- "rule is associated with some network policies".
CREATE NETWORK RULE IF NOT EXISTS IDENTIFIER($NETWORK_RULE)
    TYPE = COMPUTE_POOL MODE = INGRESS VALUE_LIST = ($COMPUTE_POOL);

CREATE NETWORK POLICY IF NOT EXISTS IDENTIFIER($NETWORK_POLICY)
    ALLOWED_NETWORK_RULE_LIST = ($NETWORK_RULE);

ALTER USER IDENTIFIER($FINANCE_USER)   SET NETWORK_POLICY = $NETWORK_POLICY;
ALTER USER IDENTIFIER($MARKETING_USER) SET NETWORK_POLICY = $NETWORK_POLICY;

-- Generate PATs. The token value is returned only once and is captured into a
-- session variable so the next statement can write it into a SECRET object.
-- On re-runs replace ADD with ROTATE PROGRAMMATIC ACCESS TOKEN; the token name
-- can only exist once per user.
ALTER USER IDENTIFIER($FINANCE_USER)
    ADD PROGRAMMATIC ACCESS TOKEN finance_pat ROLE_RESTRICTION = $FINANCE_ROLE DAYS_TO_EXPIRY = 90;
SET FINANCE_PAT = (SELECT "token_secret" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

ALTER USER IDENTIFIER($MARKETING_USER)
    ADD PROGRAMMATIC ACCESS TOKEN marketing_pat ROLE_RESTRICTION = $MARKETING_ROLE DAYS_TO_EXPIRY = 90;
SET MARKETING_PAT = (SELECT "token_secret" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

-- Wrap each PAT in a Snowflake SECRET (TYPE = password). Mounted into the container later.
USE ROLE IDENTIFIER($SERVICE_OWNER_ROLE);
USE DATABASE IDENTIFIER($DB);
USE SCHEMA   IDENTIFIER($SCH);

CREATE OR REPLACE SECRET finance_pat_secret
    TYPE = password USERNAME = $FINANCE_USER PASSWORD = $FINANCE_PAT;
CREATE OR REPLACE SECRET marketing_pat_secret
    TYPE = password USERNAME = $MARKETING_USER PASSWORD = $MARKETING_PAT;

-- CALLER grants on service_owner_role: with customer-provided creds the service runs as the
-- calling user, but the privileges it can use are the intersection of the calling user's grants
-- and the service_owner_role's CALLER grants.
USE ROLE ACCOUNTADMIN;
GRANT CALLER USAGE  ON DATABASE  IDENTIFIER($DB)        TO ROLE IDENTIFIER($SERVICE_OWNER_ROLE);
GRANT CALLER USAGE  ON SCHEMA    IDENTIFIER($SCH)       TO ROLE IDENTIFIER($SERVICE_OWNER_ROLE);
GRANT CALLER USAGE  ON WAREHOUSE IDENTIFIER($WAREHOUSE) TO ROLE IDENTIFIER($SERVICE_OWNER_ROLE);
GRANT CALLER SELECT ON TABLE     team_data              TO ROLE IDENTIFIER($SERVICE_OWNER_ROLE);

-- Image repo for the container image you'll push.
USE ROLE IDENTIFIER($SERVICE_OWNER_ROLE);
USE DATABASE IDENTIFIER($DB);
USE SCHEMA   IDENTIFIER($SCH);
CREATE IMAGE REPOSITORY IF NOT EXISTS repo;
SHOW IMAGE REPOSITORIES;
