{
 "title": "ComputePoolView",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "snow_containers_compute_pool_name",
    "label": "ComputePool",
    "query": {
     "query": "label_values(snow_containers_compute_pool_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max(spcs_container_state_running{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name))",
     "legendFormat": "running"
    },
    {
     "expr": "sum(max(spcs_container_state_started{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name))",
     "legendFormat": "started"
    },
    {
     "expr": "sum(max(spcs_container_state_pending{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name))",
     "legendFormat": "pending to start"
    },
    {
     "expr": "sum(max(spcs_container_state_finished{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name))",
     "legendFormat": "finished"
    }
   ]
  },
  {
   "title": "pending or Terminated Containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(spcs_container_state_last_finished_reason{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_node_id, reason)",
     "legendFormat": "last-terminated-reason[{{snow_node_id}}]:{{reason}}"
    },
    {
     "expr": "sum(spcs_container_state_pending_reason{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_node_id, reason)",
     "legendFormat": "pending-reason[{{snow_node_id}}]:{{reason}}"
    }
   ]
  },
  {
   "title": "Last Terminated Container Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_join(sum(spcs_container_state_last_finished_reason) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name, reason), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\", \"snow_containers_instance_name\", \"reason\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers in pending State",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "label_join(sum(spcs_container_state_pending_reason) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name, reason), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\", \"snow_containers_instance_name\", \"reason\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "label_join(sum(spcs_container_memory_used_bytes{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\")",
     "legendFormat": "Memory-{{container}}"
    },
    {
     "expr": "label_join(sum(rate(spcs_container_cpu_usage_seconds_total{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}[5m])) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\")",
     "legendFormat": "CPU-{{container}}"
    },
    {
     "expr": "label_join(avg(spcs_container_gpu_utilization{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(avg(spcs_container_gpu_memory_utilization{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Resources",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "min(spcs_node_status_allocatable{resource=\"memory\"}) by (snow_node_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(spcs_node_status_allocatable{resource=\"cpu\"}) by (snow_node_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(spcs_node_status_allocatable{resource=\"gpu\"}) by (snow_node_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(spcs_container_cpu_usage_seconds_total[5m])) by (snow_node_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(spcs_container_memory_working_set_bytes) by (snow_node_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Utilization(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spcs_container_memory_used_bytes{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_node_id) / sum(spcs_node_status_allocatable{resource=\"memory\"}) by (snow_node_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Utilization(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(spcs_container_cpu_usage_seconds_total{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}[5m])) by (snow_node_id) / sum(spcs_node_status_allocatable{resource=\"cpu\"}) by (snow_node_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node GPU Memory Utilization(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spcs_container_gpu_memory_utilization{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_node_id, gpu)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node GPU Utilization(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spcs_container_gpu_utilization{snow_containers_compute_pool_name=\"$snow_containers_compute_pool_name\"}) by (snow_node_id, gpu)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}