{
 "title": "ServiceStatus",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "snow_executable_name",
    "label": "ServiceName",
    "query": {
     "query": "label_values(snow_executable_name)"
    }
   },
   {
    "name": "snow_database_name",
    "label": "DatabaseName",
    "query": {
     "query": "label_values(snow_database_name)"
    }
   },
   { "name": "snow_schema_name", "label": "SchemaName", "query": { "query": "label_values(snow_schema_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Running Containers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(spcs_container_state_running{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name, status)",
     "legendFormat": "running - {{snow_node_id}}[{{snow_containers_container_name}}-{{snow_containers_instance_name}}]"
    }
   ]
  },
  {
   "title": "Pending to Start Containers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(spcs_container_state_pending_reason{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name, status, reason)",
     "legendFormat": "{{reason}} - [{{snow_containers_container_name}}-{{snow_containers_instance_name}}]"
    }
   ]
  },
  {
   "title": "Last Finished Reason",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(spcs_container_state_last_finished_reason{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name, status, reason)",
     "legendFormat": "{{reason}} - [{{snow_containers_container_name}}-{{snow_containers_instance_name}}]"
    }
   ]
  },
  { "title": "Service Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Resources Allocated by Containers",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(sum(spcs_container_resource_requests{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\", resource=\"cpu\"}) by (snow_containers_container_name, snow_containers_instance_name), \"join_label\", \";\", \"snow_containers_container_name\", \"snow_containers_instance_name\")\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(spcs_container_resource_limits{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\", resource=\"cpu\"}) by (snow_containers_container_name, snow_containers_instance_name), \"join_label\", \";\", \"snow_containers_container_name\", \"snow_containers_instance_name\")\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(rate(spcs_container_cpu_usage_seconds_total{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}[5m])) by (snow_containers_instance_name, snow_containers_container_name), \"join_label\", \";\", \"snow_containers_container_name\", \"snow_containers_instance_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(spcs_container_memory_used_bytes{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}) by (snow_containers_container_name, snow_containers_instance_name), \"join_label\", \";\", \"snow_containers_container_name\", \"snow_containers_instance_name\")\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(spcs_container_cpu_usage_seconds_total{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}[5m])) by (snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "spcs_container_resource_limits{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\", resource=\"cpu\"}",
     "legendFormat": "CPU - Limits"
    },
    {
     "expr": "spcs_container_resource_requests{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\", resource=\"cpu\"}",
     "legendFormat": "CPU - Requests"
    }
   ]
  },
  {
   "title": "CPU Usage Over Requests/Limits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(spcs_container_cpu_usage_seconds_total{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}[5m])) by (snow_containers_instance_name, snow_containers_container_name) / sum(spcs_container_resource_requests{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\", resource=\"cpu\"}) by (snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(spcs_container_cpu_usage_seconds_total{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}[5m])) by (snow_containers_instance_name, snow_containers_container_name) / sum(spcs_container_resource_limits{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\", resource=\"cpu\"}) by (snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "Limits"
    }
   ]
  },
  { "title": "Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(spcs_container_memory_used_bytes{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}) by (snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Over Requests/Limits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spcs_container_memory_used_bytes{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}) by (snow_containers_instance_name, snow_containers_container_name) / sum(spcs_container_resource_requests{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\", resource=\"memory\"}) by (snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(spcs_container_memory_used_bytes{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}) by (snow_containers_instance_name, snow_containers_container_name) / sum(spcs_container_resource_limits{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\", resource=\"memory\"}) by (snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(spcs_container_gpu_utilization{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}) by (snow_containers_instance_name, snow_containers_container_name) ",
     "legendFormat": "{{snow_containers_container_name}}[{{snow_containers_instance_name}}]"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(spcs_container_gpu_memory_utilization{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=\"$snow_executable_name\"}) by (snow_containers_instance_name, snow_containers_container_name) ",
     "legendFormat": "{{snow_containers_container_name}}[[{{snow_containers_instance_name}}]"
    }
   ]
  }
 ]
}