FROM nvcr.io/nvidia/pytorch:23.08-py3

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

ADD . /app

ENTRYPOINT ["python", "-u", "main.py"]