FROM nvcr.io/nvidia/pytorch:23.08-py3

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements_service.txt /app/requirements.txt
RUN pip install -r requirements.txt

ADD . /app

ENTRYPOINT ["python", "-u", "src/main_service.py"]