# Use the official Prometheus image as the base image
FROM prom/prometheus:latest

# Copy the configuration file
COPY ./metrics-consumer/bundles/otel-prom-grafana/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
