{
 "title": "ServiceStatus",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "snow_executable_name",
    "label": "ServiceName",
    "query": {
     "query": "label_values(snow_executable_name)"
    }
   },
   {
    "name": "snow_database_name",
    "label": "DatabaseName",
    "query": {
     "query": "label_values(snow_database_name)"
    }
   },
   { "name": "snow_schema_name", "label": "SchemaName", "query": { "query": "label_values(snow_schema_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Number of Running Containers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(spcs_container_state_running{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, status)",
     "legendFormat": "running: {{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}"
    }
   ]
  },
  {
   "title": "Pending to Start Containers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(20, sum(spcs_container_state_pending_reason{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name, status, reason))",
     "legendFormat": "{{reason}} - [{{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}]"
    }
   ]
  },
  {
   "title": "Last Finished Reason",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(spcs_container_state_last_finished_reason{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name, status, reason)",
     "legendFormat": "{{reason}} - [{{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}]"
    }
   ]
  },
  { "title": "Service Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Resources Allocated by Containers Over Requests and Limits",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(sum(spcs_container_resource_requests{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\", resource=\"cpu\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name), \"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\", \"snow_containers_instance_name\")\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(spcs_container_resource_limits{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\", resource=\"cpu\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name), \"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\", \"snow_containers_instance_name\")\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(rate(spcs_container_cpu_usage_seconds_total{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}[5m])) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name), \"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\", \"snow_containers_instance_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(spcs_container_memory_used_bytes{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name), \"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\", \"snow_containers_instance_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(spcs_container_resource_requests{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\", resource=\"memory\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name), \"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\", \"snow_containers_instance_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(spcs_container_resource_limits{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\", resource=\"memory\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_container_name, snow_containers_instance_name),\"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_executable_name\", \"snow_containers_container_name\", \"snow_containers_instance_name\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "topk(20, sum(rate(spcs_container_cpu_usage_seconds_total{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}[5m])) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name))",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}"
    },
    {
     "expr": "spcs_container_resource_limits{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\", resource=\"cpu\"}",
     "legendFormat": "CPU - Limits[{{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}]"
    },
    {
     "expr": "spcs_container_resource_requests{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\", resource=\"cpu\"}",
     "legendFormat": "CPU - Requests [{{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}]"
    }
   ]
  },
  {
   "title": "CPU Usage Over Requests/Limits",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(spcs_container_cpu_usage_seconds_total{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}[5m])) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name) / sum(spcs_container_resource_requests{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\", resource=\"cpu\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "Requests Usage {{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}"
    },
    {
     "expr": "sum(rate(spcs_container_cpu_usage_seconds_total{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}[5m])) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name) / sum(spcs_container_resource_limits{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\", resource=\"cpu\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "Limits Usage {{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}"
    }
   ]
  },
  { "title": "Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(spcs_container_memory_used_bytes{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage Over Requests/Limits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(spcs_container_memory_used_bytes{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name) / sum(spcs_container_resource_requests{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\", resource=\"memory\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "Requests {{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}"
    },
    {
     "expr": "sum(spcs_container_memory_used_bytes{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_instance_name, snow_containers_container_name) / sum(spcs_container_resource_limits{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\", resource=\"memory\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_instance_name, snow_containers_container_name)",
     "legendFormat": "Limits {{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(spcs_container_gpu_memory_used_mib{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name) ",
     "legendFormat": "GPU Used Memory(Mib) {{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}"
    },
    {
     "expr": "sum(spcs_container_gpu_memory_used_mib{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name) + sum(spcs_container_gpu_memory_free_mib{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name) ",
     "legendFormat": "GPU Total Memory(Mib) {{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(spcs_container_gpu_utilization{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name) ",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(spcs_container_gpu_memory_utilization{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_executable_name=~\"$snow_executable_name\"}) by (snow_database_name, snow_schema_name, snow_executable_name, snow_containers_instance_name, snow_containers_container_name) ",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_executable_name}}.{{snow_containers_container_name}}.{{snow_containers_instance_name}}"
    }
   ]
  }
 ]
}