global:
  scrape_interval: 15s
  evaluation_interval: 30s
  body_size_limit: 15MB
  sample_limit: 1500
  target_limit: 30
  label_limit: 30
  label_name_length_limit: 200
  label_value_length_limit: 200


scrape_configs:
- job_name: otel-collector
  metrics_path: /metrics
  static_configs:
  - targets: ['localhost:9001']

storage:
  tsdb:
    out_of_order_time_window: 30m
