{
 "title": "ComputePoolView",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "snow_compute_pool_name",
    "label": "ComputePool",
    "query": {
     "query": "label_values(snow_compute_pool_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Distribution",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max(container_state_running{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name))",
     "legendFormat": "running"
    },
    {
     "expr": "sum(max(container_state_started{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name))",
     "legendFormat": "started"
    },
    {
     "expr": "sum(max(container_state_pending{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name))",
     "legendFormat": "pending to start"
    },
    {
     "expr": "sum(max(container_state_finished{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name))",
     "legendFormat": "finished"
    }
   ]
  },
  {
   "title": "Containers on Compute Pool",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "label_join(sum(container_state_running{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name, snow_service_container_instance, reason), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\", \"snow_service_container_instance\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(container_state_pending{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name, snow_service_container_instance), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\", \"snow_service_container_instance\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(container_state_finished{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name, snow_service_container_instance, reason), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\", \"snow_service_container_instance\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "label_join(sum(container_memory_usage{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\")",
     "legendFormat": "Memory-{{container}}"
    },
    {
     "expr": "label_join(sum(container_cpu_usage{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\")",
     "legendFormat": "CPU-{{container}}"
    },
    {
     "expr": "label_join(avg(container_gpu_utilization{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(avg(container_gpu_memory_usage{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(avg(container_gpu_memory_used_mib{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(avg(container_gpu_memory_free_mib{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name), \"join_label\", \";\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Resources",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "min(node_memory_capacity{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(node_cpu_capacity{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_gpu_capacity{resource=\"gpu\",snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_cpu_usage{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(container_gpu_utilization{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(container_gpu_memory_usage{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true
  },
  {
   "title": "Node Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id) / sum(node_memory_capacity{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Utilization(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_cpu_usage{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id) / sum(node_cpu_capacity{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id) ",
     "legendFormat": "node: {{snow_compute_pool_node_id}}"
    }
   ]
  },
  {
   "title": "Node GPU Memory Usage (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_gpu_memory_usage{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id, gpu) / 1024 / 1024 / 1024",
     "legendFormat": "node: {{snow_compute_pool_node_id}}"
    }
   ]
  },
  {
   "title": "Node GPU Utilization(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_gpu_utilization{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id, gpu)",
     "legendFormat": "node: {{snow_compute_pool_node_id}}"
    }
   ]
  },
  {
   "title": "Block Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true
  },
  {
   "title": "Volume Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(volume_usage{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id, snow_volume_name, snow_volume_replica) / sum(volume_capacity{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id, snow_volume_name, snow_volume_replica)",
     "legendFormat": "{{snow_compute_pool_node_id}} | {{snow_volume_name}}.{{snow_volume_replica}}"
    }
   ]
  },
  {
   "title": "Volume Read Throughput (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(volume_read_throughput{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id, snow_volume_name, snow_volume_replica) / 1000 / 1000",
     "legendFormat": "{{snow_compute_pool_node_id}} | {{snow_volume_name}}.{{snow_volume_replica}}"
    }
   ]
  },
  {
   "title": "Volume Write Throughput (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(volume_write_throughput{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id, snow_volume_name, snow_volume_replica) / 1000 / 1000",
     "legendFormat": "{{snow_compute_pool_node_id}} | {{snow_volume_name}}.{{snow_volume_replica}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true
  },
  {
   "title": "Egress: Packets Received From Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(network_egress_received_packets{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress: Packets Sent To Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(network_egress_transmitted_packets{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress: Denied Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(network_egress_denied_packets{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress: Bytes Received From Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(network_egress_received_bytes{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress: Bytes Sent To Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(network_egress_transmitted_bytes{snow_compute_pool_name=\"$snow_compute_pool_name\"}) by (snow_compute_pool_node_id) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}