{
 "title": "ServiceStatus",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "snow_service_name",
    "label": "ServiceName",
    "query": {
     "query": "label_values(snow_service_name)"
    }
   },
   {
    "name": "snow_database_name",
    "label": "DatabaseName",
    "query": {
     "query": "label_values(snow_database_name)"
    }
   },
   { "name": "snow_schema_name", "label": "SchemaName", "query": { "query": "label_values(snow_schema_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Number of Running Containers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_state_running{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name)",
     "legendFormat": "running: {{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}"
    }
   ]
  },
  {
   "title": "Pending to Start Containers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(20, sum(container_state_pending_reason{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name, snow_service_container_instance, status, reason))",
     "legendFormat": "{{reason}} - [{{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}.{{snow_service_container_name}}.{{snow_service_container_instance}}]"
    }
   ]
  },
  {
   "title": "Last Finished Reason",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_state_last_finished_reason{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name, snow_service_container_instance, status, reason)",
     "legendFormat": "{{reason}} - [{{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}.{{snow_service_container_name}}.{{snow_service_container_instance}}]"
    }
   ]
  },
  { "title": "Service Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Resources Allocated by Containers Over Requests and Limits",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(sum(container_cpu_requested{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name, snow_service_container_instance), \"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\", \"snow_service_container_instance\")\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(container_cpu_limit{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name, snow_service_container_instance), \"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\", \"snow_service_container_instance\")\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(container_cpu_usage{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_instance, snow_service_container_name), \"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\", \"snow_service_container_instance\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(container_memory_usage{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name, snow_service_container_instance), \"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\", \"snow_service_container_instance\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(container_memory_requested{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name, snow_service_container_instance), \"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\", \"snow_service_container_instance\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(sum(container_memory_limit{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_name, snow_service_container_instance),\"join_label\", \".\", \"snow_database_name\", \"snow_schema_name\", \"snow_service_name\", \"snow_service_container_name\", \"snow_service_container_instance\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(container_cpu_usage{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_instance, snow_service_container_name)",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}.{{snow_service_container_name}}.{{snow_service_container_instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "GiB" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_instance, snow_service_container_name) / 1024 / 1024 / 1024",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}.{{snow_service_container_name}}.{{snow_service_container_instance}}"
    }
   ]
  },
  {
   "title": "Egress: Bytes Received From Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(network_egress_received_bytes{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_instance, snow_service_container_name)",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}.{{snow_service_container_name}}.{{snow_service_container_instance}}"
    }
   ]
  },
  {
   "title": "Egress: Packets Received From Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(network_egress_received_packets{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_instance, snow_service_container_name)",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}.{{snow_service_container_name}}.{{snow_service_container_instance}}"
    }
   ]
  },
  {
   "title": "Egress: Bytes Sent To Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(network_egress_transmitted{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_instance, snow_service_container_name)",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}.{{snow_service_container_name}}.{{snow_service_container_instance}}"
    }
   ]
  },
  {
   "title": "Egress: Bytes Sent To Internet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(network_egress_transmitted_packets{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_instance, snow_service_container_name)",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}.{{snow_service_container_name}}.{{snow_service_container_instance}}"
    }
   ]
  },
  { "title": "GPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_gpu_utilization{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_instance, snow_service_container_name) ",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}.{{snow_service_container_name}}.{{snow_service_container_instance}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "GiB" } },
   "targets": [
    {
     "expr": "sum(container_gpu_memory_usage{snow_database_name=\"$snow_database_name\", snow_schema_name=\"$snow_schema_name\", snow_service_name=~\"$snow_service_name\"}) by (snow_database_name, snow_schema_name, snow_service_name, snow_service_container_instance, snow_service_container_name) / 1024 / 1024 / 1024",
     "legendFormat": "{{snow_database_name}}.{{snow_schema_name}}.{{snow_service_name}}.{{snow_service_container_name}}.{{snow_service_container_instance}}"
    }
   ]
  }
 ]
}