receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'spcs-metrics'
        http_sd_configs:
          - url: 'http://localhost:9003'

exporters:
 datadog:
  api:
   site: ${DATADOG_METRICS_SITE}
   key: ${DATADOG_METRICS_KEY}

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [datadog]
